repos:
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.0
    hooks:
      - id: gitleaks
        name: gitleaks
        description: Scan for secrets using gitleaks
        entry: gitleaks detect --source git -v
        language: golang
        pass_filenames: false
        always_run: true
        stages: [commit]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: detect-private-key
        name: Detect private keys
        description: Detect presence of private keys
        entry: detect-private-key
        language: python
        types: [text]
